# Generated by Django 3.2.9 on 2021-11-27 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_house_total_energy'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Bedroom', max_length=150)),
                ('room_type', models.CharField(choices=[('Kitchen', 'Kitchen'), ('Bedroom', 'Bedroom'), ('Common_Area', 'Common_Area')], max_length=100)),
                ('energy_use', models.IntegerField()),
                ('no_of_appliances', models.SmallIntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='house',
            name='rooms',
            field=models.ManyToManyField(to='core.Room'),
        ),
    ]
